# Generated by Django 4.2.7 on 2023-12-04 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_subscription_slug_alter_subscription_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscription',
            new_name='SubscriptionPlan',
        ),
    ]
