# Generated by Django 4.2.7 on 2023-12-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='days',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
