# Generated by Django 4.2.7 on 2023-12-05 18:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_subscriptionplan_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='date_started',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
