# Generated by Django 4.2.7 on 2023-12-05 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0007_alter_subscription_date_ended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='ref',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
