# Generated by Django 4.2.7 on 2023-12-04 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='doc',
            field=models.FileField(default='FR', upload_to='docs/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='plan_type',
            field=models.CharField(choices=[('FR', 'FREE'), ('BS', 'BASIC'), ('PR', 'PREMINUM')], default='FR', max_length=2),
        ),
    ]
